services:
  app:
    container_name: easyblog
    build:
      context: .
      target: deploy
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 500M
    ports:
      - 8080:8080
    volumes:
      - ./easy/db/:/app/db/:rw
    environment:
      - DATABASE_LOC=/app/db/blog.db
    restart: always

volumes:
  easyblog-db-data:
